merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path

from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),

    path('listings/', views.listing_list, name='listing-list'),
    path('listings/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listings/add/', views.listing_create, name='listing-create'),
    path('listings/<int:id>/change/', views.listing_update, name='listing-update'),
    path('listings/<int:id>/delete/', views.listing_update, name='listing-delete'),

    path('about-us/', views.about, name='about'),
    path('contact-us/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),
]

merchex/listings/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Band(models.Model):

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
       validators=[MinValueValidator(1900),
                   MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORDS = 'R'
        CLOTHING = 'C'
        POSTERS = 'P'
        MISC = 'M'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        null=True,
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2021)]
    )
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms

from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField()


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ('active', 'official_homepage')


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render

from listings.models import Band, Listing
from listings.forms import BandForm, ContactUsForm, ListingForm


def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})


def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # create a new `Band` and save it to the db
            band = form.save()
            # redirect to the detail page of the band we just created
            return redirect('band-detail', band.id)
    else:
        form = BandForm()

    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # update the existing `Band` in the database
            form.save()
            # redirect to the detail page of the `Band` we just updated
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                  'listings/band_update.html',
                  {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # we need this for both GET and POST

    if request.method == 'POST':
        # delete the band from the database
        band.delete()
        # redirect to the bands list
        return redirect('band-list')

    # no need for an `else` here. If it's a GET request, just continue

    return render(request,
                  'listings/band_delete.html',
                  {'band': band})


def listing_list(request):
    listings = Listing.objects.all()
    return render(request,
                  'listings/listing_list.html',
                  {'listings': listings})


def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request,
                  'listings/listing_detail.html',
                  {'listing': listing})


def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listing-list')
    else:
        form = ListingForm()

    return render(request,
                  'listings/listing_create.html',
                  {'form': form})


def listing_update(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm(instance=listing)

    return render(request,
                  'listings/listing_update.html',
                  {'form': form})


def listing_delete(request, id):
    listing = Listing.objects.get(id=id)

    if request.method == 'POST':
        listing.delete()
        return redirect('listing-list')

    return render(request,
                  'listings/listing_delete.html',
                  {'listing': listing})


def about(request):
    return render(request, 'listings/about.html')


def contact(request):
    if request.method == 'POST':
        # create an instance of our form, and fill it with the POST data
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonymous"} via MerchEx Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return redirect('email-sent')
        # if the form is not valid, we let execution continue to the return
        # statement below, and display the form again (with errors).

    else:
        # this must be a GET request, so create an empty form
        form = ContactUsForm()

    return render(request,
                  'listings/contact.html',
                  {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>About Us</h1>

  <p>We love merch!</p>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Delete Band</h1>

  <p>Are you sure you want to delete this band?: {{ band.name }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
  </form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>{{ band.name }}</h1>

  <ul>
    <li>Genre: {{ band.get_genre_display }}</li>
    <li>Year formed: {{ band.year_formed }}</li>
    <li>Active: {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
      <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
  </ul>

  <p>{{ band.biography }}</p>

  <a href="{% url 'band-update' band.id %}">Edit this Band</a>
  <a href="{% url 'band-delete' band.id %}">Delete band</a>

  <h2>Listings</h2>
  <ul>
    {% for listing in band.listing_set.all %}
      <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
    {% endfor %}
  </ul>

  <a href="{% url 'band-list' %}">Back to all Bands</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Bands</h1>

  <a href="{% url 'band-create' %}">Create new Band</a>

  <ul>
    {% for band in bands %}
      <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-update' band.id %}">[edit]</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Update Band</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
  <head>
    <title>Merchex</title>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
  </head>
  <body>

    <nav>
      <a href="{% url 'band-list' %}">Bands</a>
      <a href="{% url 'listing-list' %}">Listings</a>
      <a href="{% url 'about' %}">About Us</a>
      <a href="{% url 'contact' %}">Contact Us</a>
    </nav>

     {% block content %}{% endblock %}

  </body>
</html>

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Email Sent</h1>

  <p>We'll be in touch ASAP.</p>

{% endblock %}

merchex/listings/templates/listings/hello.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Hello Django!</h1>

  <p>My favourite bands are:</p>

  <ul>
    {% for band in bands %}
      <li>{{ band.name }}</li>
    {% endfor %}
  </ul>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Create new Listing</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>

{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Delete Listing</h1>

  <p>Are you sure you want to delete this listing?: {{ listing.title }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
  </form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

  <h2>{{ listing.title }}</h2>

  <ul>
    <li>Type: {{ listing.get_type_display }}</li>
    <li>Year of origin: {{ listing.year }}</li>
    <li>Sold: {{ listing.sold|yesno }}</li>
  </ul>

  <p>{{ listing.description }}</p>

  <a href="{% url 'listing-update' listing.id %}">Edit this Listing</a>
  <a href="{% url 'listing-delete' listing.id %}">Delete listing</a>
  <a href="{% url 'listing-list' %}">Back to all Listings</a>

{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Listings</h1>

  <p>Check out the latest listings below!</p>

  <ul>
    {% for listing in listings %}
      <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-update' listing.id %}">[edit]</a>
      </li>
    {% endfor %}
  </ul>

{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Update Listing</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>

{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'listings/base.html' %}

{% block content %}

  <h1>Listings</h1>

  <p>Check out the latest listings below!</p>

  <ul>
    {% for listing in listings %}
      <li>{{ listing.title }}</li>
    {% endfor %}
  </ul>

{% endblock %}